### ISSUE TITLE
"synthetic NLQs" and "annotated NLQs"

### ISSUE THREAD

**Issue by huimoran** [shuaichenchang/ODIS-Text-to-SQL#1]
Hello. I see here that you mentioned "In the demonstration examples, we replace the annotated NLQs with these synthetic NLQs while keeping the SQL queries unchanged. This setup allows the  LLMs to be exposed to the in-domain SQL distribution while remaining unaware of the annotated in-domain NLQs or other  inputs beyond its own generated NLQs".

 I don't quite understand what "synthetic NLQs" and "annotated NLQs" are, can you explain them to me? 

It is better to explain with some examples, so that I can understand all your research more easily. Thank you

![domen](https://github.com/shuaichenchang/ODIS-Text-to-SQL/assets/100472413/bd03ec75-ae46-4b04-917d-0ee0ac14fb9e)

**Comment by shuaichenchang** [comment]
Hi huimoran, thank you for your interest in our work! An annotated example refers to the actual NLQ from a user paired with its corresponding SQL query, i.e. an actual example from the dataset. In this context, we aim to study the roles of the in-domain SQL queries, where the SQL queries are always from the datasets. The term "annotated NLQs" refer to the actual NLQs from users corresponding to these SQL queries, while "synthetic NLQs" denotes the NLQs that are generated from the actual SQL queries using a LLM. This process is also known as SQL-to-text generation.

For example, an actual example could be (1) NLQ: How many singers are there in the database? (2)SQL: Select count(*) From singer; Then for the SQL query "Select count(*) From singer;" the annotated NLQ is "How many singers are there in the database?", while a synthetic NLQ could be "number of singers". The language style (distribution) between annotated NLQs and synthetic NLQs can be different.

**Comment by huimoran** [comment]
Thank you for your patient explanation. Your explanation is very clear. I understand.
